runtime: nodejs
env: standard

env_variables:
  # Database connection string
  DB_USER: "covergen-user"
  DB_DATABASE: "covergen"
  INSTANCE_CONNECTION_NAME: "your-project-id:your-region:your-instance-id"
  NODE_ENV: "production"
  DB_PASSWORD: "projects/[PROJECT_ID]/secrets/DB_PASSWORD/versions/latest"
  DB_PORT: "5432"